apiVersion: v1
kind: Service
metadata:
  name: kubernetes-configmap-reload
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-configmap-reload
  ports:
    - name: http
      protocol: TCP
      port: 8081